export default [
    {
        id: 1,
        title: '버즈 라이브 하드케이스',
        price: 13900,
        description:
            '폴리카보네이트 소재로 버즈 라이브를 든든하게 보호해주며 무광재질로 한층 더 고급스럽게 만들어 줍니다.',
        category: '모바일',
        image: '/images/product_1.jpg',
        rating: { rate: 5, count: 10 },
        quantity: 1,
        itemtotal: 13900,
    },
    {
        id: 2,
        title: '데일리 주머니(소)',
        price: 6500,
        description:
            '귀여운 에스더버니의 작은 주머니예요. 가방 속에 소중한 물건을 넣어서 가져다니기 좋아요.',
        category: '액세서리',
        image: '/images/product_2.jpg',
        rating: { rate: 4.9, count: 6 },
        quantity: 1,
        itemtotal: 6500,
    },
    {
        id: 3,
        title: '4단 점착 메모지',
        price: 3500,
        description:
            '잊고 싶지 않은 메모를 어디든 붙여 에스더버니와 함께 해요!',
        category: '문구류',
        image: '/images/product_3.jpg',
        rating: { rate: 4.7, count: 20 },
        quantity: 1,
        itemtotal: 3500,
    },
    {
        id: 4,
        title: '메세지 카드',
        price: 2000,
        description: '에스더버니 메세지 카드로 따뜻한 마음을 전하세요.',
        category: '문구류',
        image: '/images/product_4.jpg',
        rating: { rate: 4.8, count: 30 },
        quantity: 1,
        itemtotal: 2000,
    },
    {
        id: 5,
        title: '안경 케이스 닦이 세트',
        price: 12000,
        description:
            '사랑스러운 에스더버니 안경 케이스와 안경 닦이가 세트로 나왔어요.',
        category: '리빙',
        image: '/images/product_5.jpg',
        rating: { rate: 4.9, count: 40 },
        quantity: 1,
        itemtotal: 12000,
    },
    {
        id: 6,
        title: '플라워 랜덤 인형',
        price: 18900,
        description:
            '에스더버니들의 꽃 속의 작은 요정으로 찾아왔어요. 꽃밭에서 스페셜 에스더버니를 찾아보세요.',
        category: '인형',
        image: '/images/product_6.jpg',
        rating: { rate: 5, count: 15 },
        quantity: 1,
        itemtotal: 18900,
    },
    {
        id: 7,
        title: '에어팟 프로 하드 케이스',
        price: 16900,
        description:
            '폴리카보네이트 소재로 우리의 소중한 에어팟 프로를 든든하게 보호해주며 무광재질로 한층 더 고급스러움을 제공합니다.',
        category: '모바일',
        image: '/images/product_7.jpg',
        rating: { rate: 4.9, count: 25 },
        quantity: 1,
        itemtotal: 16900,
    },
    {
        id: 8,
        title: '클립 3종 세트',
        price: 7000,
        description:
            '책을 읽을 때나 서류를 정리할 때, 언제 어디서나 유용하게 쓰이는 클립!',
        category: '리빙',
        image: '/images/product_8.jpg',
        rating: { rate: 5, count: 8 },
        quantity: 1,
        itemtotal: 7000,
    },
    {
        id: 9,
        title: '데코 프레임 스티커',
        price: 2300,
        description: '러블리 에스더버니가 데코 프레임 스티커로 찾아왔습니다.',
        category: '문구류',
        image: '/images/product_9.jpg',
        rating: { rate: 5, count: 10 },
        quantity: 1,
        itemtotal: 2300,
    },
    {
        id: 10,
        title: '스윗데이트 랜덤 인형 키링',
        price: 18900,
        description:
            '에스더버니들의 달콤한 데이트가 있는 날이예요. 스윗한 에스더버니 인형 키링을 만나보세요.',
        category: '인형',
        image: '/images/product_10.jpg',
        rating: { rate: 4.9, count: 10 },
        quantity: 1,
        itemtotal: 18900,
    },
    {
        id: 11,
        title: '콜렉트 북 1단',
        price: 15000,
        description:
            '에스더버니가 콜렉트북으로 찾아왔어요. 나의 소중한 사진을 더욱 특별하게 보관하세요.',
        category: '문구류',
        image: '/images/product_11.jpg',
        rating: { rate: 5, count: 10 },
        quantity: 1,
        itemtotal: 15000,
    },
    {
        id: 12,
        title: '러블리 납작 파우치',
        price: 8000,
        description: '키치키치한 에스더버니의 일상을 엿볼 수 있는 파우치예요.',
        category: '액세서리',
        image: '/images/product_12.jpg',
        rating: { rate: 5, count: 10 },
        quantity: 1,
        itemtotal: 8000,
    },
];
